### ISSUE TITLE
The file exported by superset in CSV format appears Chinese gibberish

### ISSUE THREAD

**Issue by MLikeWater** [Kyligence/Insight-for-Superset#2]
### superset report show
![image](https://user-images.githubusercontent.com/19518068/44018344-062944b8-9f0e-11e8-8aec-5490e49d2307.png)

### export CSV file
The exported CSV format is as follows:

![image](https://user-images.githubusercontent.com/19518068/44018359-12756288-9f0e-11e8-8490-bd884aef6abf.png)

### solution
This problem is caused by the language format supported by Superset itself, and the exported format needs to be configured in superset_config.py:
```
CSV_EXPORT = {
    'encoding' : 'utf_8_sig',
}
```
### test result
Modify the configuration file, start the container, and download the CSV file, which is as follows: 
![image](https://user-images.githubusercontent.com/19518068/44020372-43c14676-9f14-11e8-9e88-3a6b260a0e49.png)

**Comment by zhaoyongjie** [comment]
@jiangshouzhuang  Thank you for your feedback. we will expose this config when container start

**Comment by MLikeWater** [comment]
@zhaoyongjie OK, I will close the issue.

**Comment by quanyu2626** [comment]
Thanks for your feedback, please see this [documention](https://github.com/Kyligence/Insight-for-Superset/blob/master/Documents/user_manual_cn/superset_cn.rst#%E5%AF%BC%E5%87%BAcsv%E6%96%87%E4%BB%B6)
@jiangshouzhuang
